### ISSUE TITLE
support for angular 5 components

### ISSUE THREAD

**Issue by jpdonaghy** [ike18t/mock_component#5]
Failed: No annotation or decoration metadata on your component
Error: No annotation or decoration metadata on your component
	    at getComponentSelector (node_modules/mock-component/dist/lib/mock_component.js:49:11)
	    at Object.MockComponent (node_modules/mock-component/dist/lib/mock_component.js:15:19)

**Comment by ike18t** [comment]
I'm almost done with this.  I wanted to convert the tests to testbed tests which took me a while to get working.

**Comment by ike18t** [comment]
7df64a8
